package utils;

public enum PropertiesMapper {
    URL,
    SELENIUMHUB,
    SELENIUMPORT,
    BROWSERNAME,
    ENVIRONMENT,
    EXECUTIONMODE,
    SOUCELAB_USERNAME,
    SOUCELAB_ACCESSKEY,
    SOUCELAB_PLATFORM,
    SOUCELAB_VERSION,
    SOUCELAB_BUILD,
    SOUCELAB_NAME,
    SOUCELAB_URL
}
